name: GHCR CI
on: [push, workflow_dispatch]

permissions:
  contents: read
  packages: write

jobs:
  build-and-push:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Login to GHCR
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: jiyufor  # 硬编码你的用户名
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Build and push
        uses: docker/build-push-action@v6
        with:
          push: true
          tags: ghcr.io/jiyufor/hajimi:latest
          # 关键修改：完全删除缓存配置
          platforms: linux/amd64
