name: GHCR CI

on:
  push:
    branches: [main]
  workflow_dispatch:

jobs:
  build-and-push:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write  # 必须要有这个权限

    steps:
    - name: Checkout repository
      uses: actions/checkout@v4

    - name: Read version from file
      id: version
      run: echo "VERSION=$(cat version.txt | grep version= | cut -d= -f2)" >> $GITHUB_OUTPUT

    - name: Log in to GHCR
      uses: docker/login-action@v3
      with:
        registry: ghcr.io
        username: ${{ github.actor }}  # 自动使用你的用户名（Jiyufor）
        password: ${{ secrets.GITHUB_TOKEN }}  # 使用默认Token

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v3

    - name: Build and push
      uses: docker/build-push-action@v6
      with:
        context: .
        push: true
        tags: |
          ghcr.io/jiyufor/hajimi:latest  # 关键修改：直接写死你的用户名（全小写）
          ghcr.io/jiyufor/hajimi:${{ steps.version.outputs.VERSION }}  # 同样全小写
        platforms: linux/amd64  # 单平台确保成功
